services:
  msa_db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: msa_db
    volumes:
      - db_main_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  msa_users_db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: msa_users_db
    volumes:
      - db_users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  users_service:
    build:
      context: ./users_service
      dockerfile: Dockerfile
    depends_on:
      - msa_users_db
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/users_db
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8001:8000"
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","80"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - msa_db
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/main_db
      USERS_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:8000"
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","80"]

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - users_service

volumes:
    db_main_data:
    db_users_data:
